name: Maven CI

on:
 push:
    branches: [ master ]
    
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
 
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2      

    - name: Install freedomotic-ja-loader
      run: mvn install:install-file -Dfile=third-party-libs/freedomotic-jar-loader-0.0.1.jar -DgroupId=com.freedomotic -DartifactId=freedomotic-jar-loader -Dversion=0.0.1 -Dpackaging=jar
          
    - name: Build and test project with Maven
      run: mvn install

  publish-job:
      runs-on: ubuntu-latest
      needs: [build_and_test]

      steps:
        - uses: actions/checkout@v2
        - uses: rlespinasse/github-slug-action@v4
        
        - uses: actions/setup-java@v1
          with:
            java-version: 11
        - run: mvn install:install-file -Dfile=third-party-libs/freedomotic-jar-loader-0.0.1.jar -DgroupId=com.freedomotic -DartifactId=freedomotic-jar-loader -Dversion=0.0.1 -Dpackaging=jar
        - run: mvn install -DskipTests
        - run: mkdir staging && cp framework/freedomotic-core/target/release/*.zip staging
        
        - uses: actions/upload-artifact@v1
          with:
            name: freedomotic-5.6.0-${{ env.GITHUB_SHA_SHORT }}.zip
            path: staging
            
        - name: Update dailybuild release
          uses: eine/tip@master
          with:
            tag: dailybuild
            rm: true
            token: ${{ secrets.GITHUB_TOKEN }}
    
